from enum import Enum
from .tz import zones

class SquareSortOrderEnum(Enum):
  ASC="ASC"
  DESC="DESC"

class SquareCatalogCustomAttributeDefinitionTypeEnum(Enum):
  STRING="STRING"
  BOOLEAN="BOOLEAN"
  NUMBER="NUMBER"
  SELECTION="SELECTION"

class SquareCatalogPricingTypeEnum(Enum):
  FIXED_PRICING="FIXED_PRICING"
  VARIABLE_PRICING="VARIABLE_PRICING"

class SquareItemTypeEnum(Enum):
  ITEM="ITEM"
  IMAGE="IMAGE"
  CATEGORY="CATEGORY"
  ITEM_VARIATION="ITEM_VARIATION"
  ITEM_OPTION_VAL="ITEM_OPTION_VAL"
  TAX="TAX"
  DISCOUNT="DISCOUNT"
  MODIFIER_LIST="MODIFIER_LIST"
  PRICING_RULE="PRICING_RULE"
  PRODUCT_SET="PRODUCT_SET"
  TIME_PERIOD="TIME_PERIOD"
  MEASUREMENT_UNIT="MEASUREMENT_UNIT"
  SUBSCRIPTION_PLAN="SUBSCRIPTION_PLAN" 
  ITEM_OPTION="ITEM_OPTION"
  CUSTOM_ATTRIBUTE_DEFINITION="CUSTOM_ATTRIBUTE_DEFINITION"
  QUICK_AMOUNT_SETTINGS="QUICK_AMOUNT_SETTINGS"

class SquareTaxIdEnum(Enum):
  eu_vat="eu_vat"
  fr_siret="fr_siret"
  fr_naf="fr_naf"
  es_nif="es_nif"

class SquareLocationTypeEnum(Enum):
  PHYSICAL="PHYSICAL"
  MOBILE="MOBILE"

class SquareLocationCapabilitiesEnum(Enum):
  CREDIT_CARD_PROCESSING="CREDIT_CARD_PROCESSING"
  AUTOMATIC_TRANSFERS="AUTOMATIC_TRANSFERS"
  UNLINKED_REFUNDS="UNLINKED_REFUNDS"

class SquareStatusEnum(Enum):
  ACTIVE="ACTIVE"
  INACTIVE="INACTIVE"

class SquareDayOfWeekEnum(Enum):
  SUN="SUN"
  MON="MON"
  TUE="TUE"
  WED="WED"
  THU="THU"
  FRI="FRI"
  SAT="SAT"

class SquareJobAssignmentTypeEnum(Enum):
  ALL_CURRENT_AND_FUTURE_LOCATIONS="ALL_CURRENT_AND_FUTURE_LOCATIONS"
  EXPLICIT_LOCATIONS="EXPLICIT_LOCATIONS"

class SquareJobAssignmentPayTypeEnum(Enum):
  NONE="NONE"
  HOURLY="HOURLY"
  SALARY="SALARY"

class SquareInventoryAlertEnum(Enum):
  NONE="NONE"
  LOW_QUALITY="LOW_QUALITY"

class SquareCatalogItemProductTypeEnum(Enum):
  REGULAR="REGULAR"
  GIFT_CARD="GIFT_CARD"
  APPOINTMENTS_SERVICE="APPOINTMENTS_SERVICE"


class SquareTaxCalculationPhaseEnum(Enum):
  TAX_SUBTOTAL_PHASE="TAX_SUBTOTAL_PHASE"
  TAX_TOTAL_PHASE="TAX_TOTAL_PHASE"

class SquareTaxInclusionTypeEnum(Enum):
  ADDITIVE="ADDITIVE"
  INCLUSIVE="INCLUSIVE"

class SquareCatalogDiscountTypeEnum(Enum):
  FIXED_PERCENTAGE="FIXED_PERCENTAGE"
  FIXED_AMOUNT="FIXED_AMOUNT"
  VARIABLE_PERCENTAGE="VARIABLE_PERCENTAGE"
  VARIABLE_AMOUNT="VARIABLE_AMOUNT"


class SquareCatalogDiscountModifyTaxBasisEnum(Enum):
  MODIFY_TAX_BASIS="MODIFY_TAX_BASIS"
  DO_NOT_MODIFY_TAX_BASIS="DO_NOT_MODIFY_TAX_BASIS"

class SquareCatalogModifierListSelectionTypeEnum(Enum):
  SINGLE="SINGLE"
  MULTIPLE="MULTIPLE"

class SquareExcludeStrategyEnum(Enum):
  LEAST_EXPENSIVE="LEAST_EXPENSIVE"
  MOST_EXPENSIVE="MOST_EXPENSIVE"

class SquareMeasurementUnitAreaEnum(Enum):
  IMPERIAL_ACRE="IMPERIAL_ACRE"
  IMPERIAL_SQUARE_INCH="IMPERIAL_SQUARE_INCH"
  IMPERIAL_SQUARE_FOOT="IMPERIAL_SQUARE_FOOT"
  IMPERIAL_SQUARE_YARD="IMPERIAL_SQUARE_YARD"
  IMPERIAL_SQUARE_MILE="IMPERIAL_SQUARE_MILE"
  METRIC_SQUARE_CENTIMETER="METRIC_SQUARE_CENTIMETER"
  METRIC_SQUARE_METER="METRIC_SQUARE_METER"
  METRIC_SQUARE_KILOMETER="METRIC_SQUARE_KILOMETER"

class SquareMeasurementUnitLengthEnum(Enum):
  IMPERIAL_INCH="IMPERIAL_INCH"
  IMPERIAL_FOOT="IMPERIAL_FOOT"
  IMPERIAL_YARD="IMPERIAL_YARD"
  IMPERIAL_MILE="IMPERIAL_MILE"
  METRIC_MILLIMETER="METRIC_MILLIMETER"
  METRIC_CENTIMETER="METRIC_CENTIMETER"
  METRIC_METER="METRIC_METER"
  METRIC_KILOMETER="METRIC_KILOMETER"

class SquareMeasurementUnitVolumeEnum(Enum):
  GENERIC_FLUID_OUNCE="GENERIC_FLUID_OUNCE"
  GENERIC_SHOT="GENERIC_SHOT"
  GENERIC_CUP="GENERIC_CUP"
  GENERIC_PINT="GENERIC_PINT"
  GENERIC_QUART="GENERIC_QUART"
  GENERIC_GALLON="GENERIC_GALLON"
  IMPERIAL_CUBIC_INCH="IMPERIAL_CUBIC_INCH"
  IMPERIAL_CUBIC_FOOT="IMPERIAL_CUBIC_FOOT"
  IMPERIAL_CUBIC_YARD="IMPERIAL_CUBIC_YARD"
  METRIC_MILLILITER="METRIC_MILLILITER"
  METRIC_LITER="METRIC_LITER"

class SquareMeasurementUnitWeightEnum(Enum):
  IMPERIAL_WEIGHT_OUNCE="IMPERIAL_WEIGHT_OUNCE"
  IMPERIAL_POUND="IMPERIAL_POUND"
  IMPERIAL_STONE="IMPERIAL_STONE"
  METRIC_MILLIGRAM="METRIC_MILLIGRAM"
  METRIC_GRAM="METRIC_GRAM"
  METRIC_KILOGRAM="METRIC_KILOGRAM"

class SquareMeasurementUnitGenericEnum(Enum):
  UNIT="UNIT"

class SquareMeasurementUnitTimeEnum(Enum):
  GENERIC_MILLISECOND="GENERIC_MILLISECOND"
  GENERIC_SECOND="GENERIC_SECOND"
  GENERIC_MINUTE="GENERIC_MINUTE"
  GENERIC_HOUR="GENERIC_HOUR"
  GENERIC_DAY="GENERIC_DAY"

class SquareMeasurementUnitTypeEnum(Enum):
  TYPE_CUSTOM="TYPE_CUSTOM"
  TYPE_AREA="TYPE_AREA"
  TYPE_LENGTH="TYPE_LENGTH"
  TYPE_VOLUME="TYPE_VOLUME"
  TYPE_WEIGHT="TYPE_WEIGHT"
  TYPE_GENERIC="TYPE_GENERIC"

class SquareSubcriptionCadenceEnum(Enum):
  DAILY="DAILY"
  WEEKLY="WEEKLY"
  EVERY_TWO_WEEKS="EVERY_TWO_WEEKS"
  THIRTY_DAYS="THIRTY_DAYS"
  SIXTY_DAYS="SIXTY_DAYS"
  NINETY_DAYS="NINETY_DAYS"
  MONTHLY="MONTHLY"
  EVERY_TWO_MONTHS="EVERY_TWO_MONTHS"
  QUARTERLY="QUARTERLY"
  EVERY_FOUR_MONTHS="EVERY_FOUR_MONTHS"
  EVERY_SIX_MONTHS="EVERY_SIX_MONTH"
  ANNUAL="ANNUAL"
  EVERY_TWO_YEARS="EVERY_TWO_YEARS"

class SquareCatalogCustomAttributeDefinitionTypeEnum(Enum):
  STRING="STRING"
  BOOLEAN="BOOLEAN"
  NUMBER="NUMBER"
  SELECTION="SELECTION"

class SquareProductEnum(Enum):
  SQUARE_POS="SQUARE_POS"
  EXTERNAL_API="EXTERNAL_API"
  BILLING="BILLING"
  APPOINTMENTS="APPOINTMENTS"
  INVOICES="INVOICES"
  ONLINE_STORE="ONLINE_STORE"
  PAYROLL="PAYROLL"
  DASHBOARD="DASHBOARD"
  ITEM_LIBRARY_IMPORT="ITEM_LIBRARY_IMPORT"
  OTHER="OTHER"

class SquareCatalogCustomAttributeDefinitionSellerVisibilityEnum(Enum):
  SELLER_VISIBILITY_HIDDEN="SELLER_VISIBILITY_HIDDEN"
  SELLER_VISIBILITY_READ_WRITE_VALUES="SELLER_VISIBILITY_READ_WRITE_VALUES"

class SquareCatalogCustomAttributeDefinitionAppVisibilityEnum(Enum):
  APP_VISIBILITY_HIDDEN="APP_VISIBILITY_HIDDEN"
  APP_VISIBILITY_READ_ONLY="APP_VISIBILITY_READ_ONLY"
  APP_VISIBILITY_READ_WRITE_VALUES="APP_VISIBILITY_READ_WRITE_VALUES"

class SquareCatalogQuickAmountsSettingsOptionEnum(Enum):
  DISABLED="DISABLED"
  MANUAL="MANUAL"
  AUTO="AUTO"

class SquareCatalogQuickAmountTypeEnum(Enum):
  QUICK_AMOUNT_TYPE_MANUAL = "QUICK_AMOUNT_TYPE_MANUAL"
  QUICK_AMOUNT_TYPE_AUTO = "QUICK_AMOUNT_TYPE_AUTO"

class SquareBookingStatusEnum(Enum):
  PENDING="PENDING"
  CANCELLED_BY_CUSTOMER="CANCELLED_BY_CUSTOMER"
  CANCELLED_BY_SELLER="CANCELLED_BY_SELLER"
  DECLINED="DECLINED"
  ACCEPTED="ACCEPTED"
  NO_SHOW="NO_SHOW"

class SquareBusinessAppointmentSettingsBookingLocationTypeEnum(Enum):
  BUSINESS_LOCATION="BUSINESS_LOCATION"
  CUSTOMER_LOCATION="CUSTOMER_LOCATION"
  PHONE="PHONE"

class SquareBookingCreatorDetailsCreatorTypeEnum(Enum):
  TEAM_MEMBER="TEAM_MEMBER"
  CUSTOMER="CUSTOMER"

class SquareBookingBookingSourceEnum(Enum):
  FIRST_PARTY_MERCHANT="FIRST_PARTY_MERCHANT"
  FIRST_PARTY_BUYER="FIRST_PARTY_BUYER"
  THIRD_PARTY_BUYER="THIRD_PARTY_BUYER"
  API="API"

class SquareCardBrandEnum(Enum):
  OTHER_BRAND="OTHER_BRAND"
  VISA="VISA"
  MASTERCARD="MASTERCARD"
  AMERICAN_EXPRESS="AMERICAN_EXPRESS"
  DISCOVER="DISCOVER"
  DISCOVER_DINERS="DISCOVER_DINERS"
  JCB="JBC"
  CHINA_UNIONPAY="CHINA_UNIONPAY"
  SQUARE_GIFT_CARD="SQUARE_GIFT_CARD"
  SQUARE_CAPITAL_CARD="SQUARE_CAPITAL_CARD"
  INTERAC="INTERAC"
  EFTPOS="EFTPOS"
  FELICA="FELICIA"
  EBT="EBT"

class SquareCardCoBrandEnum(Enum):
  UNKNOWN="UNKNOWN"
  AFTERPAY="AFTERPAY"
  CLEARPAY="CLEARPAY"

class SquareCardTypeEnum(Enum):
  CREDIT="CREDIT"
  DEBIT="DEBIT"

class SquareCardPrepaidTypeEnum(Enum):
  NOT_PREPAID="NOT_PREPAID"
  PREPAID="PREPAID"

class SquareSortOrderEnum(Enum):
  ASC="ASC"
  DESC="DESC"

class SquareSearchCatalogItemsRequestStockLevelEnum(Enum):
  OUT = "OUT"
  LOW = "LOW"

class SquareCatalogItemProductTypeForFilterEnum(Enum):
  REGULAR="REGULAR"
  GIFT_CARD = "GIFT_CARD"
  APPOINTMENTS_SERVICE = "APPOINTMENTS_SERVICE"

class SquareCatalogStockConversion(Enum):
  stockable_item_variation_id = "stockable_item_variation_id"
  stockable_quantity = "stockable_quantity"
  nonstockable_quantity = "nonstockable_quantity"

class SquarePaymentStatusEnum(Enum):
  APPROVED="APPROVED"
  PENDING="PENDING"
  COMPLETED="COMPLETED"
  CANCELED="CANCELED"
  FAILED="FAILED"

class SquareProcessingFeeTypeEnum(Enum):
  INITIAL="INITIAL"
  ADJUSTMENT="ADJUSTEMENT"

class SquarePaymentDelayActionEnum(Enum):
  CANCEL="CANCEL"
  COMPLETE="COMPLETE"

class SquarePaymentSourceTypeEnum(Enum):
  CARD="CARD"
  BANK_ACCOUNT="BANK_ACCOUNT"
  WALLET="WALLET"
  BUY_NOW_PAY_LATER="BUY_NOW_PAY_LATER"
  CASH="CASH"
  EXTERNAL="EXTERNAL"

class SquarePaymentCardStatusEnum(Enum):
  AUTHORIZED="AUTHORIZED"
  CAPTURED="CAPTURED"
  VOIDED="VOIDED"
  FAILED="FAILED"

class SquareCardEntryMethodEnum(Enum):
  KEYED="KEYED"
  SWIPED="SWIPED"
  EMV="EMV"
  ON_FILE="ON_FILE"
  CONTACTLESS="CONTACTLESS"

class SquareCardCVVStatusEnum(Enum):
  CVV_ACCEPTED="CVV_ACCEPTED"
  CVV_REJECTED="CVV_REJECTED"
  CVV_NOT_CHECKED="CVV_NOT_CHECKED"

class SquareCardAVSStatusEnum(Enum):
  AVS_ACCEPTED="AVS_ACCEPTED"
  AVS_REJECTED="AVS_REJECTED"
  AVS_NOT_CHECKED="AVS_NOT_CHECKED"

class SquareCardVerificationMethodEnum(Enum):
  PIN="PIN"
  SIGNATURE="SIGNATURE"
  PIN_AND_SIGNATURE="PIN_AND_SIGNATURE"
  ON_DEVICE="ON_DEVICE"
  NONE="NONE"

class SquareEVMPaymentResultEnum(Enum):
  SUCCESS="SUCCESS"
  FAILURE="FAILURE"
  UNKNOWN="UNKNOWN"

class SquareBankAccountOwnershipTypeEnum(Enum):
  INDIVIDUAL="INDIVIDUAL"
  COMPANY="COMPANY"
  UNKNOWN="UNKNOWN"

class SquareBankAccountTypeEnum(Enum):
  CHECKING="CHECKING"
  SAVINGS="SAVINGS"
  UNKNOWN="UNKNOWN"

class SquareExternalPaymentTypeEnum(Enum):
  CHECK="CHECK"
  BANK_TRANSFER="BANK_TRANSFER"
  OTHER_GIFT_CARD="OTHER_GIFT_CARD"
  CRYPTO="CRYPTO"
  SQUARE_CASH="SQUARE_CASH"
  SOCIAL="SOCIAL"
  EXTERNAL="EXTERNAL"
  EMONEY="EMONEY"
  CARD="CARD"
  STORED_BALANCE="STORED_BALANCE"
  FOOD_VOUCHER="FOOD_VOUCHER"
  OTHER="OTHER"

class SquareDigitalWalletStatusEnum(Enum):
  AUTHORIZED="AUTHORIZED"
  CAPTURED="CAPTURED"
  VOIDED="VOIDED"
  FAILED="FAILED"

class SquareDigitalWalletBrandEnum(Enum):
  CASH_APP="CASH_APP"
  PAYPAY="PAYPAY"
  UNKNOWN="UNKNOWN"

class SquareRiskEvaluationRiskLevelEnum(Enum):
  PENDING="PENDING"
  NORMAL="NORMAL"
  MODERATE="MODERATE"
  HIGH="HIGH"

class SquarePaymentCapabilitiesEnum(Enum):
  EDIT_AMOUNT_UP="EDIT_AMOUNT_UP"
  EDIT_AMOUNT_DOWN="EDIT_AMOUNT_DOWN"
  EDIT_TIP_AMOUNT_UP="EDIT_TIP_AMOUNT_UP"
  EDIT_TIP_AMOUNT_DOWN="EDIT_TIP_AMOUNT_DOWN"
  EDIT_DELAY_ACTION="EDIT_DELAY_ACTION"

class SquareApplicationDetailsExternalSquareProductEnum(Enum):

  APPOINTMENTS="APPOINTMENTS"
  ECOMMERCE_API="ECOMMERCE_API"
  INVOICES="INVOICES"
  ONLINE_STORE="ONLINE_STORE"
  OTHER="OTHER"
  RESTAURANTS="RESTAURANTS"
  RETAIL="RETAIL"
  SQUARE_POS="SQUARE_POS"
  TERMINAL_API="TERMINAL_API"
  VIRTUAL_TERMINAL="VIRTUAL_TERMINAL"


class SquareBokingStatusEnum(Enum):

  PENDING="PENDING"
  CANCELLED_BY_CUSTOMER="CANCELLED_BY_CUSTOMER"
  CANCELLED_BY_SELLER="CANCELLED_BY_SELLER"
  DECLINED="DECLINED"
  ACCEPTED="ACCEPTED"
  NO_SHOW="NO_SHOW"

class SquareBookingBookingLocationTypeEnum(Enum):
  BUSINESS_LOCATION="BUSINESS_LOCATION"
  CUSTOMER_LOCATION="CUSTOMER_LOCATION"
  PHONE="PHONE"

class SquareBookingCreatorTypeEnum(Enum):
  TEAM_MEMBER="TEAM_MEMBER"
  CUSTOMER="CUSTOMER"

class SquareBookingSourceTypeEnum(Enum):
  FIRST_PARTY_MERCHANT="FIRST_PARTY_MERCHANT"
  FIRST_PARTY_BUYER="FIRST_PARTY_BUYER"
  THIRD_PARTY_BUYER="THIRD_PARTY_BUYER"
  API="API"

SquareTimeZoneEnum = Enum('SquareTimeZoneEnum', dict([(i, i) for i in zones]))